name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - flake8
  - pandas
  - numpy
  - sqlalchemy
  - scikit-learn
  - pyodbc
  - jupyterlab
  - jupyter
  - psycopg2
  - requests
  - google-auth
  - google-cloud-bigquery
  - google-cloud-datastore
  - boto3
  - flask
  - dash
  - ConfigArgParse
  - beautifulsoup4
  - bcrypt
  - pylint
  - shap
  - xgboost
  - scikit-learn
  - seaborn