name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - flake8
  - pandas
  - sqlalchemy
  - scikit-learn
  - pyodbc
  - jupyterlab
  - psycopg2
  - requests
  - google-auth
  - google-cloud-bigquery
  - google-cloud-datastore
  - boto3
  - flask
  - dash
  - ConfigArgParse
  - beautifulsoup4
  - bcrypt
